name: publish

on:
  push:
    branches: [ "main" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.actor }}/nest-deploy:latest

jobs:
    publish:
        name: Build and push image
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v3
        - name: Login
          run: |
            echo ${{ secrets.PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        - name: Build and Publish
          run: |
            docker build . --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
            docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

    deploy:
        needs: publish
        name: Deploy image
        runs-on: ubuntu-latest
        env:
          APPTOKEN: ${{ secrets.PAT }}
          USERNAME: ${{ secrets.SSH_USER }}
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          envs: APPTOKEN,USERNAME

        steps:
        - name: Install ssh keys
          # check this thread to understand why its needed:
          # <https://stackoverflow.com/a/70447517>
          script: |
            echo $APPTOKEN | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            cd ${{ secrets.WORK_DIR }}
            docker compose -f ./docker-compose.yml